hash-format = "sha256"

[[files]]
file = "config/alexscaves-client.toml"
hash = "db5c9fddb7816fae75ecdb86e604c97408eca8626d785b9380a0b39d68b8bd58"

[[files]]
file = "mods/ai-improvements.pw.toml"
hash = "eed03a69cacac3a826fc07806ad069b0ae605fefcedab2b2b8fcfa060eb60ebb"
metafile = true

[[files]]
file = "mods/alexs-caves.pw.toml"
hash = "0cbc4b2c6b58b7a94f030ae84f18057e5dc78a17bad429f40b8884926a6ab233"
metafile = true

[[files]]
file = "mods/alexs-delight.pw.toml"
hash = "99f6d4e46f784953d16aa1ce5f72327b21487dc0e27d3143c8a6b60c6d02381a"
metafile = true

[[files]]
file = "mods/alexs-mobs.pw.toml"
hash = "5e1239fd67c97c042d09cf38664698c9d1a3cfbc50d779fc550c461cf6aeb565"
metafile = true

[[files]]
file = "mods/alexscaves-client.toml"
hash = "db5c9fddb7816fae75ecdb86e604c97408eca8626d785b9380a0b39d68b8bd58"

[[files]]
file = "mods/almost-unified.pw.toml"
hash = "e1a222c5ace6d1b4bab067b1245e460179a153f1e7bc8538335056fa8442155c"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "793693a85f3c87d4e899ee0c58deabc53690bf5a70f17343f28fd5063ce8a1e1"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "4e81241ba2da06f425efc5e09fb6b38470125c1581c39e1310c5843a0b96ec76"
metafile = true

[[files]]
file = "mods/artsandcrafts-compatibility.pw.toml"
hash = "5761962afde8b830b84f795ad4d339fb800b8b0832e3a781eaded41ab30478a6"
metafile = true

[[files]]
file = "mods/artsandcrafts.pw.toml"
hash = "4b9ef302a517601cdec1a0177164831ad57678ea3acace59053c8e0013a900d3"
metafile = true

[[files]]
file = "mods/auudio.pw.toml"
hash = "6620a1c58f283e37cbb1b73a82644808bf635817bd5fda6676d48e150acc994f"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f8b6ef08945410e1341212a2723477487fb66a2c8fd67dd201433658791d298d"
metafile = true

[[files]]
file = "mods/bellsandwhistles.pw.toml"
hash = "126db1f1ec01bbc4cf3393e087363e2fdbfe4a3face897ed27985b14a1a519a9"
metafile = true

[[files]]
file = "mods/berry-good.pw.toml"
hash = "c410ef1d053db4fc3fccde5331fa3ebac561e0e2f6f4babe9110b9c322fbc95a"
metafile = true

[[files]]
file = "mods/blood-magic.pw.toml"
hash = "34021b5e1c4725156f1d864fc637efb43dfb96ee473c65716982fb0bcd3c1223"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "55ab212ba17d188a2f95b65d4cf63bbc98c664aa74986b57d288d12e62bac780"
metafile = true

[[files]]
file = "mods/blueprint.pw.toml"
hash = "90fc66d49d29c1b1a5b14c5d571d628c6853f7f0519b04e74e14399c75cd08c6"
metafile = true

[[files]]
file = "mods/brewin-and-chewin.pw.toml"
hash = "d47b75b30e711de67e9de2ce05fd5979a89e5aacb5c0fd036c6f9466b1da2665"
metafile = true

[[files]]
file = "mods/chimes.pw.toml"
hash = "d960f68e4c5e5f79eff91a277dc22d7acb49f04080fcf0fe1648b5a9a83e3d4f"
metafile = true

[[files]]
file = "mods/chisels-bits.pw.toml"
hash = "aca009f78e1223d44ba4b9683537d7acdd899b30834e25ab04a3092156725bcf"
metafile = true

[[files]]
file = "mods/citadel.pw.toml"
hash = "0c8838dba7d2090968ca9ec633260d42ca16f1df186a780bd5965994541d9f74"
metafile = true

[[files]]
file = "mods/compat-delight.pw.toml"
hash = "f1f2ac0a30c1b2912e335f3d36b02a22af8b962385ed0a68bdcfa46cc83b9498"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "4063abe583282834b2f78e3b3e6b9ee4d231a680f74c020e405a4ef196f21ee4"
metafile = true

[[files]]
file = "mods/copycats.pw.toml"
hash = "853df4ab2418f347cbb1e3b4ca6c82b2a517a8e4e8ccabcd42c27e3496707a32"
metafile = true

[[files]]
file = "mods/corpse.pw.toml"
hash = "2fba2317a375669ccb1376525d4d4e0d1903cc5dc44fc70dce1d0e3dbb6aacb1"
metafile = true

[[files]]
file = "mods/create-big-cannons.pw.toml"
hash = "9eb4f3e7a5a83c588e0caa676d91597c18f2c8004c9e57a10e72859e474fa0e5"
metafile = true

[[files]]
file = "mods/create-central-kitchen.pw.toml"
hash = "0b69f772db857977d0e70bad04d4a8112f0963074ca07258efb44d2d3e5f4578"
metafile = true

[[files]]
file = "mods/create-cobblestone.pw.toml"
hash = "cc93c7dd457427c7a6db51fe412a53771e2e6d6539d312d5141b050a32d45fb2"
metafile = true

[[files]]
file = "mods/create-deco.pw.toml"
hash = "87be52b8aaa9864eab1ec2df8c862cd01a084989b07c4cdbfaa21c57a9a778a6"
metafile = true

[[files]]
file = "mods/create-enchantment-industry.pw.toml"
hash = "c670ae9055f10dafb61fe340583c361f4c41ed45671c9440bae1f0696b47252a"
metafile = true

[[files]]
file = "mods/create-mobile-packages.pw.toml"
hash = "62d198c4aaaf86c010de6b0e3933c09424f17380842a3dfd28123676eaa31632"
metafile = true

[[files]]
file = "mods/create-steam-n-rails.pw.toml"
hash = "5391ac307bbc73edb72e7eb11495af96e327eff1c02ff67d2ebbe615ca6766d7"
metafile = true

[[files]]
file = "mods/create.pw.toml"
hash = "fb5c251cf4997fa65ca043bab7c9ecbd02e108031584a3e26276b77d212de23c"
metafile = true

[[files]]
file = "mods/create_oxidized.pw.toml"
hash = "46a8e2d0b10f2c1aec37850dccea50c99ebbf8435108b246017bddeb2b12e847"
metafile = true

[[files]]
file = "mods/createaddition.pw.toml"
hash = "e6d1f36e9e0193fe410d136e0cda8a7f6dbbc809c0644f06a601bddf5b38a395"
metafile = true

[[files]]
file = "mods/curios.pw.toml"
hash = "9eefd607e0d54ec444e798ccdeede1a09a3939440bd1e11c11b84c07a5134be2"
metafile = true

[[files]]
file = "mods/decorative-blocks.pw.toml"
hash = "dc23ac7c75b3f33b93f5725c9d6cfb2e62575550f2b8b01683397e35ad1a3955"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "47fd33da68d0b13cdffd4124f5bc9cff64caa2878ce7e979ba8092400c2ae1eb"
metafile = true

[[files]]
file = "mods/drippy-loading-screen.pw.toml"
hash = "e0d378e3a1c413c67634413187f138838e198df51d3481d77216747bd6d9d2da"
metafile = true

[[files]]
file = "mods/dungeons_delight.pw.toml"
hash = "5a9c0b4bb162a8edfd2541b4d30e691b98e389068e5a9c6f9d9b4248ad7a5044"
metafile = true

[[files]]
file = "mods/dustrial-decor.pw.toml"
hash = "f55c33bbcf1b7d49b0ab93345a4e311f36c30f7c3177cf5c70d91c973a95c029"
metafile = true

[[files]]
file = "mods/embeddium.pw.toml"
hash = "5ec0c37f3f4ad07a40c10376668bca80334ddb7ad2bab06eb4de8f7aac339c8e"
metafile = true

[[files]]
file = "mods/escalated.pw.toml"
hash = "43101636762df8cbe9180587aa0eaf3c7234da8e5bcbf1e6e0a7dbcd58dca40b"
metafile = true

[[files]]
file = "mods/every-compat.pw.toml"
hash = "79e9e769665eee2dcd21f86d352c247606913b5c804a4afa07c2f57071fd444b"
metafile = true

[[files]]
file = "mods/exposure.pw.toml"
hash = "ce198cf0e4ac56f35c03b5e721eacbd6c6bc86b6ab318c4c7259082edb625fc2"
metafile = true

[[files]]
file = "mods/fairy-lights.pw.toml"
hash = "eeca094798607a0393a5ec261a0f3298e20fa74b0daa879951aec47c2c7fe64b"
metafile = true

[[files]]
file = "mods/fancymenu.pw.toml"
hash = "2023ed56ff0d7566f898a1be5e542bcde94fbc252264dface9cd9dacc0883c38"
metafile = true

[[files]]
file = "mods/farmers-delight.pw.toml"
hash = "9f2ffb0d4c65fcb2a96878287a7119459b9d0637c395e5097d691416690d6563"
metafile = true

[[files]]
file = "mods/fastfurnace.pw.toml"
hash = "932ddad36de5cc064fd285cff392872050de95e262029d336e99f44e0ce01d97"
metafile = true

[[files]]
file = "mods/fastworkbench.pw.toml"
hash = "77095e78d0432b58d1243f271e953c8c6b318bf8dbd0563358b07e15baf30a9c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "902bac905b93271f02bd0951a22bac06a3da24f5c237fcaeb469e14a7679e508"
metafile = true

[[files]]
file = "mods/figura.pw.toml"
hash = "7b411f636c4a61db20882904e79625750ff1230c83763a0a426c04a8bbf8d7f1"
metafile = true

[[files]]
file = "mods/framework.pw.toml"
hash = "376f8a190f00bd120193d7a665ebe1b03dfe329cc395f7d944f7216c1182c84d"
metafile = true

[[files]]
file = "mods/gems-realm.pw.toml"
hash = "ae5469a605102e8be36dbf74e6735ecd56c6a41ba8a8a0299ac522da7b175813"
metafile = true

[[files]]
file = "mods/guideme.pw.toml"
hash = "2e42b3a809ec9b027e23714e01c255fe5111a9d4cd58fad114dd0f2aa75c0d7e"
metafile = true

[[files]]
file = "mods/hexerei.pw.toml"
hash = "6b75e21a40b8dcfe80a1d29ce4b8b3168b07f1329688de128f49bafb802d169b"
metafile = true

[[files]]
file = "mods/interiors.pw.toml"
hash = "7ca55cd661721ca944979439aac5160009e07ce2568fbf8aee53e019f3e55fba"
metafile = true

[[files]]
file = "mods/inventory-essentials.pw.toml"
hash = "9779719134e508c31ef0cb08ed272daef6d3b4a8a5bff07e48f9695e88e5a410"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "0fbcc8cf03336e6bed425e2115fc4ff1a3a05be5c655228b305e70380eb08b57"
metafile = true

[[files]]
file = "mods/jei.pw.toml"
hash = "b0441c2b5bb6ff680d97eac28d95847f0d4dbee34d1d42d897997b500acd44ca"
metafile = true

[[files]]
file = "mods/jinxedlib.pw.toml"
hash = "05e33822164b9f498943e51e9502aefadb504ec1551174bad7e96e8066d2f35a"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "dca44614a72da5f7d2d57823cc54aaf3335d652c1a447a6e5df2e60365a6ea95"
metafile = true

[[files]]
file = "mods/just-enough-archaeology.pw.toml"
hash = "f222191613aeed690136f205c906cdde6363d58bf0a3604515abcea73f5e482d"
metafile = true

[[files]]
file = "mods/just-enough-resources-jer.pw.toml"
hash = "02977d28acd2089c39dbe5b65fd08e78094fb650b4afc810f757cb5cea1fbda8"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "90a70141bcec839b6a1aa647c91f97bb7b33b6b9e6ce6b3b18a4113aa7dff636"
metafile = true

[[files]]
file = "mods/kotlin-for-forge.pw.toml"
hash = "70a4ecd9d0c04ad20aeb976c1ee28933ce48a0a1f43df42deafaeb2ad7235297"
metafile = true

[[files]]
file = "mods/lexiconfig.pw.toml"
hash = "471f6366615d29246e35c3193359ea479925ad98eb2beb1d59f0647f9896df3d"
metafile = true

[[files]]
file = "mods/lodestonelib.pw.toml"
hash = "dfb4b7c9a2085a665e87ebc3d60045e3173bb602e7b3de94e29d37168083345d"
metafile = true

[[files]]
file = "mods/malum.pw.toml"
hash = "00a16f6cc02ad9f0825138857da26e6bf5c0f65dc5d4d40705b091e29176d3a2"
metafile = true

[[files]]
file = "mods/melody.pw.toml"
hash = "c9f8bce06b85e4dbfdaecc7d0930bf7f4fabccc7967f867b7eb7acb8dd5b77a7"
metafile = true

[[files]]
file = "mods/miners-delight.pw.toml"
hash = "67a9681bb1944cb09e596d30905be4ab72f5478b5abaa67a45737a51824ae648"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "c3fe09de76654cbd7012ab476423de1eb1e3ae80cc2a3aec7ff547560e1b56c9"
metafile = true

[[files]]
file = "mods/morph-o-tool.pw.toml"
hash = "33b81bba2d8a156fb1115be572f01c4e7e4bc76d83421bfa3c884e75880bdeeb"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "8b3dc6fa116657eba16f3550bd6468ba4aab315c35952d1de7c2d165033b3a2d"
metafile = true

[[files]]
file = "mods/patchouli.pw.toml"
hash = "55c6d0b8ee25fd6a37a964805de3d2eab3f20d73a88ba77a63b4a51fd985d9dd"
metafile = true

[[files]]
file = "mods/placebo.pw.toml"
hash = "045d582e2c534c5bb96d7336b4ae2cd12692c6de29b19ae5f1dbfd8759c03b03"
metafile = true

[[files]]
file = "mods/plushie-buddies.pw.toml"
hash = "3ffd980d60e72eb2261ae4b72c500a79b12a5ed976f7c2b86c83f56d0af54fab"
metafile = true

[[files]]
file = "mods/portable-crafting-table.pw.toml"
hash = "1fd8a2699c76037a8b14ee761a9e4520cba05105b26394d08e9bdf7e87e8a918"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "d83c43aa5cd92ee3427f79fcf1d4e4ecf763972aa4a9ea6eac87d865c2fe955f"
metafile = true

[[files]]
file = "mods/refurbished-furniture.pw.toml"
hash = "2bcee75d08b33dd6506b7cd3f67ea9d0d2c1bf14e26728fa8e12ef19c895b165"
metafile = true

[[files]]
file = "mods/resourceful-config.pw.toml"
hash = "b85e8417e797be3fdae046c487eeda8f54cdc88f3f20e462e0e229f8dd734214"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "5c07edd0c8fe82e85efd6c027476ba54cf98291526803b74614c3436292e4ab6"
metafile = true

[[files]]
file = "mods/rpl.pw.toml"
hash = "93128d85ae0b3be9c8248b09f3a63ed88c746568480cc7e9a8e2a9b4bd13477c"
metafile = true

[[files]]
file = "mods/rs-requestify.pw.toml"
hash = "20e0c41d2278b2f07ad6b6ad1857b6488546f603ee933c6fe4233ad3eaaa75b0"
metafile = true

[[files]]
file = "mods/runiclib.pw.toml"
hash = "2dbe8c4d2e526717bb37fca847e0d7e42c2f65575e90883b096a2cd2787ccb30"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "b8c7497acbf4890b4609b6b20de7affdd3482fc99af975d9ff6b29c075e1d8a7"
metafile = true

[[files]]
file = "mods/simple-radio.pw.toml"
hash = "60a3b1aa962b013468fbaf732b7b7e5e04734ed0e8f09e7eed84b2da3e01ab0a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a4206ffef9707744ab06842f9c79342bf048e3183a624d2295fb9e851cc90ded"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "f49c7302f7a044aae67740fac3a7558ca2f26b3a89a69a3940d516a40e3b75b7"
metafile = true

[[files]]
file = "mods/sophisticated-backpacks.pw.toml"
hash = "0023efff6ba97c0d4f291c239f6566f3d4d40d183d0eaa25eacb7558aa2a7dd5"
metafile = true

[[files]]
file = "mods/sophisticated-core.pw.toml"
hash = "03875711b2137496e8f94990ad2a8d2efeaa7eeafab4dece340287d4900d89f5"
metafile = true

[[files]]
file = "mods/stone-zone.pw.toml"
hash = "debea00134b24debeb7b7b10bb3150a6d01f727cdc0b9e4817e71206e0a1b618"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "ff765c8249ef581bc6eef2ab9304f519aeec2552dc7a57760b7cd88eadd2685d"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3848bc11aa2acabef74eb85ca74b8ca8e23733b7fcbc77293165c5c7161e3288"
metafile = true

[[files]]
file = "mods/table-top-craft.pw.toml"
hash = "c8597c7c0d8768c1dbef6cbcc7d45846933aa0528074bf41878e7cf0683f6a1f"
metafile = true

[[files]]
file = "mods/tempad.pw.toml"
hash = "0ebc212bb83219ecd2b24d3943ab84a905c5f0963b04755fcf816d3b7744dc6b"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "14117b94c456598c9acece143c7a0da3cf56d13182d035a74a2da8a52dd19cbd"
metafile = true

[[files]]
file = "mods/uppers.pw.toml"
hash = "7d4883117ff8ab8e5d54204a7b5fa9ebbc4a8fae3f6cb5e8c1484d5c4b682705"
metafile = true

[[files]]
file = "mods/visuality-reforged.pw.toml"
hash = "7d26046aea03fcae4f1e5875d818543a5a401e2ae239cdfe3f18307309014290"
metafile = true
