name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f2e63ee3067e9e9a9f498f93cf688949cad027e76a0d0291de98f520a9be2ca"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
