name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "11854a67bf334241345f55aa8d0883c6d980207b819ad01063906b41746cd69a"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
