name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5255f2bec3349c811ca153d346a10daf83a48e7a5b9c57dcae96c93ad6608cba"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
