name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bc513c172167ee7feeb1196e3ce0caf0a0d1ee4d02ff8729816af6207bb111c8"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
