name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "16a870c68e23f29a44241c1bf0e029ef31d65b02ba7773d849573ce7bfa407ad"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
