name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c053f5b146b33c4e373327fd6cedb9d4bfd67d708a0ccae53b8f04eb3b6d581"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
