name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db7c1237c350358129ccc2e537244da636d5be23ec65ff095e4ab4ec67821348"

[versions]
forge = "47.4.13"
minecraft = "1.20.1"
