name = "Poobcraft"
author = "Reaxt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b654d29c8b514d3824ae8ffe500dd1d5c4e766433c8b55d8d56c557728469a2e"

[versions]
forge = "47.4.10"
minecraft = "1.20.1"
