# This is a basic workflow to help you get started with Actions

name: Pull pack

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["refreshpack"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pullpack:
    environment: ssh
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: ./sshtest.sh thjis
        
      - name: sleep a little
        run: sleep 10
        
      - name: Run another
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: ./sshtest.sh work?s
