# This is a basic workflow to help you get started with Actions

name: Pull pack

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["refreshpack"]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  pullpack:
    environment: ssh
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - name: Pull data
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: ./serverpull.sh
      - name: Inform of server shutdown
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: ./sshsay.sh "Server will restart in 1 minute!"
      - name: Wait a minute!
        run: sleep 60
      - name: Restart the server!
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST}}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVKEY }}
          script: systemctl --user restart poob.service
